### ISSUE TITLE
Double transpose of same matrix

### ISSUE THREAD

**Issue by filchy** [naivelamb/kaggle-cloud-organization#10]
Hello,
at this function
https://github.com/naivelamb/kaggle-cloud-organization/blob/08750c89d56235eee68c8827afb075610e53569d/make_folds.py#L24
you convert rle to mask at `def rle2mask` and transpose final mask matrix.
https://github.com/naivelamb/kaggle-cloud-organization/blob/08750c89d56235eee68c8827afb075610e53569d/util/utils.py#L331
But then in next function `def mask2rle` you transpose that matrix again which means that the matrix is same as before.
https://github.com/naivelamb/kaggle-cloud-organization/blob/08750c89d56235eee68c8827afb075610e53569d/util/utils.py#L308
So can I ask you please what is the reason of this transposing. Thank you very much for your answer.

**Comment by naivelamb** [comment]
Fot this dataset, The pixels are indexed from top to bottom, left to right when generating rle. Hence, we need to do the transpose to make the mask shape in the format (height, weight). Same thing applies when converting mask to rle.
ref: https://www.kaggle.com/c/understanding_cloud_organization/overview/evaluation

**Comment by filchy** [comment]
Thank you very much.
